// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BackendQuota struct {
	BackendName string
	BytesUsed   int64
	BytesLimit  int64
	UpdatedAt   pgtype.Timestamptz
}

type BackendUsage struct {
	BackendName  string
	Period       string
	ApiRequests  int64
	EgressBytes  int64
	IngressBytes int64
	UpdatedAt    pgtype.Timestamptz
}

type MultipartPart struct {
	UploadID   string
	PartNumber int32
	Etag       string
	SizeBytes  int64
	CreatedAt  pgtype.Timestamptz
}

type MultipartUpload struct {
	UploadID    string
	ObjectKey   string
	BackendName string
	ContentType *string
	CreatedAt   pgtype.Timestamptz
}

type ObjectLocation struct {
	ObjectKey   string
	BackendName string
	SizeBytes   int64
	CreatedAt   pgtype.Timestamptz
}
