// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: replication.sql

package db

import (
	"context"
)

const getUnderReplicatedObjects = `-- name: GetUnderReplicatedObjects :many
WITH under_replicated AS (
    SELECT object_key
    FROM object_locations
    GROUP BY object_key
    HAVING COUNT(*) < $1::bigint
    LIMIT $2
)
SELECT ol.object_key, ol.backend_name, ol.size_bytes, ol.created_at
FROM object_locations ol
JOIN under_replicated ur ON ol.object_key = ur.object_key
ORDER BY ol.object_key, ol.created_at ASC
`

type GetUnderReplicatedObjectsParams struct {
	Factor  int64
	MaxKeys int32
}

func (q *Queries) GetUnderReplicatedObjects(ctx context.Context, arg GetUnderReplicatedObjectsParams) ([]ObjectLocation, error) {
	rows, err := q.db.Query(ctx, getUnderReplicatedObjects, arg.Factor, arg.MaxKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ObjectLocation{}
	for rows.Next() {
		var i ObjectLocation
		if err := rows.Scan(
			&i.ObjectKey,
			&i.BackendName,
			&i.SizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertReplicaConditional = `-- name: InsertReplicaConditional :one
INSERT INTO object_locations (object_key, backend_name, size_bytes, created_at)
SELECT $1, $2, ol.size_bytes, NOW()
FROM object_locations ol
WHERE ol.object_key = $1 AND ol.backend_name = $3
ON CONFLICT (object_key, backend_name) DO NOTHING
RETURNING true AS inserted
`

type InsertReplicaConditionalParams struct {
	ObjectKey     string
	BackendName   string
	BackendName_2 string
}

func (q *Queries) InsertReplicaConditional(ctx context.Context, arg InsertReplicaConditionalParams) (bool, error) {
	row := q.db.QueryRow(ctx, insertReplicaConditional, arg.ObjectKey, arg.BackendName, arg.BackendName_2)
	var inserted bool
	err := row.Scan(&inserted)
	return inserted, err
}
